<?php require VIEWS_PATH . '/includes/header.phtml'; ?>
<div class="container">
    <div class="row">
        <!--        <div class="col-md-6">-->
        <!--            <h1>Users</h1>-->
        <!--            --><?php //foreach ($this->users as $user): ?>
        <!--                <h3>--><? //= $user['NAME']; ?><!--</h3>-->
        <!--            --><?php //endforeach; ?>
        <!--        </div>-->

        <div class="jumbotron container">
            <h1>
                <i class="fa fa-truck"></i>
                Products
            </h1>
        </div>

        <?php foreach ($this->products as $product): ?>
        <div class="col-md-4">
            <img src="http://via.placeholder.com/350x150?text=CODE" alt="" class="img-responsive">
            <h3>
                <a href="<?=HOME;?>product/<?=$product['slug'];?>">
                    <?=$product['name'];?>
                </a>
            </h3>
            <span><?= 'R$ ' . number_format($product['price'], 2, ',', '.'); ?></span>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php require VIEWS_PATH . '/includes/footer.phtml'; ?>
