<?php
/**
 * Created by PhpStorm.
 * User: tommye
 * Date: 16/12/17
 * Time: 09:15
 */

require VIEWS_PATH . 'includes/header.phtml';

?>
<div class="container">
    <div class="row">
        <div class="jumbotron container">
            <h1>
                <i class="fa fa-sign-in"></i>
                Register
            </h1>
        </div>

        <!-- Example row of columns -->
        <div class="col-md-12">
            <?php require VIEWS_PATH . 'includes/message.phtml';?>
        </div>

        <div class="col-md-6" style="border-right: 1px solid #CCC;">
            <form action="<?=HOME . 'signup/new';?>" method="POST">
                <h2>Cadastrar</h2>
                <hr>
                <div class="form-group">
                    <label for="exampleInputEmail1">Nome(*)</label>
                    <input type="text" class="form-control" placeholder="Nome" name="name" <?php if(isset($_POST['name'])):?> value="<?=$_POST['name'];?>" <?php endif;?>>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Email(*)</label>
                    <input type="email" class="form-control" placeholder="Email" name="email" <?php if(isset($_POST['email'])):?> value="<?=$_POST['email'];?>" <?php endif;?>>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Password(*)</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                </div>

                <button type="submit" class="btn btn-info">Cadastrar & Continuar</button>
            </form>
        </div>

        <div class="col-md-6 col-lg-6">
            <h2>Autenticar</h2>
            <hr>
            <form action="<?=HOME . 'signup/login';?>" method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email(*)</label>
                    <input type="email" class="form-control" placeholder="Email" name="email" <?php if(isset($_POST['email'])):?> value="<?=$_POST['email'];?>" <?php endif;?>>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Password(*)</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                </div>

                <div class="form-group">
                    <label>&nbsp;</label>
                    <input class="form-control" style="border: 0px solid rgba(255,255,255,.5); cursor: default;">
                </div>

                <button type="submit" class="btn btn-success">Logar & Continuar</button>
            </form>
        </div>
    </div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>